"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: opensource@swisssign.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swisssign_ra_api.v2
from swisssign_ra_api.v2.model.certificate import Certificate
from swisssign_ra_api.v2.model.certificate_revocation_status import CertificateRevocationStatus
from swisssign_ra_api.v2.model.null_type import NullType
globals()['Certificate'] = Certificate
globals()['CertificateRevocationStatus'] = CertificateRevocationStatus
globals()['NullType'] = NullType
from swisssign_ra_api.v2.model.certificate_order_certificate import CertificateOrderCertificate


class TestCertificateOrderCertificate(unittest.TestCase):
    """CertificateOrderCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateOrderCertificate(self):
        """Test CertificateOrderCertificate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CertificateOrderCertificate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
