# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swisssign_ra_api.v2.models.additional_recipient import AdditionalRecipient

class TestAdditionalRecipient(unittest.TestCase):
    """AdditionalRecipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdditionalRecipient:
        """Test AdditionalRecipient
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdditionalRecipient`
        """
        model = AdditionalRecipient()
        if include_optional:
            return AdditionalRecipient(
                email = 'shared.mailbox@sample.org',
                recipient_type = 'DNS_OWNER_CHECK_EMAIL_LINK',
                language = 'NEUTRAL'
            )
        else:
            return AdditionalRecipient(
                email = 'shared.mailbox@sample.org',
                recipient_type = 'DNS_OWNER_CHECK_EMAIL_LINK',
                language = 'NEUTRAL',
        )
        """

    def testAdditionalRecipient(self):
        """Test AdditionalRecipient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
