# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swisssign_ra_api.v2.models.request_ip import RequestIP

class TestRequestIP(unittest.TestCase):
    """RequestIP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestIP:
        """Test RequestIP
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestIP`
        """
        model = RequestIP()
        if include_optional:
            return RequestIP(
                values = [
                    '1.1.1.1'
                    ]
            )
        else:
            return RequestIP(
                values = [
                    '1.1.1.1'
                    ],
        )
        """

    def testRequestIP(self):
        """Test RequestIP"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
