"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md  # noqa: E501

    The version of the OpenAPI document: 2.2.1
    Contact: ssc@swisssign.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swisssign_ra_api.v2
from swisssign_ra_api.v2.model.job_status import JobStatus
from swisssign_ra_api.v2.model.job_type import JobType
globals()['JobStatus'] = JobStatus
globals()['JobType'] = JobType
from swisssign_ra_api.v2.model.certificate_order_task import CertificateOrderTask


class TestCertificateOrderTask(unittest.TestCase):
    """CertificateOrderTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateOrderTask(self):
        """Test CertificateOrderTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CertificateOrderTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
