# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swisssign_ra_api.v2.models.client_dns import ClientDNS

class TestClientDNS(unittest.TestCase):
    """ClientDNS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientDNS:
        """Test ClientDNS
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientDNS`
        """
        model = ClientDNS()
        if include_optional:
            return ClientDNS(
                uuid = 'cld-10877aec-412f-4b96-a5d4-f5f95da8634e',
                domain = 'xn--dj-kia8a.vu.com',
                domain_unicode = 'déjà.vu.com',
                validated = True,
                trusted_domain = True,
                time_validated = '2022-01-12T23:20:50.52Z',
                validation_method = 'cabdns',
                random_value = '',
                random_value_time_created = '2022-01-12T23:20:50.52Z',
                random_value_time_expire = '2022-01-12T23:20:50.52Z',
                validation_result = 'Validated XYZ ...',
                time_expired = '2022-01-12T23:20:50.52Z',
                expired = False,
                random_value_time_expired = False,
                status = 'NOT_VALIDATED'
            )
        else:
            return ClientDNS(
                uuid = 'cld-10877aec-412f-4b96-a5d4-f5f95da8634e',
                domain = 'xn--dj-kia8a.vu.com',
                domain_unicode = 'déjà.vu.com',
                validated = True,
                trusted_domain = True,
                validation_method = 'cabdns',
                expired = False,
                random_value_time_expired = False,
        )
        """

    def testClientDNS(self):
        """Test ClientDNS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
