# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swisssign_ra_api.v2.models.api_error import APIError

class TestAPIError(unittest.TestCase):
    """APIError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIError:
        """Test APIError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIError`
        """
        model = APIError()
        if include_optional:
            return APIError(
                uuid = '123e4567-e89b-12d3-a456-426614174000',
                error_code = '<000.000.0000>',
                error_messages = [
                    'Invalid identifier for product xyz'
                    ]
            )
        else:
            return APIError(
                uuid = '123e4567-e89b-12d3-a456-426614174000',
                error_code = '<000.000.0000>',
                error_messages = [
                    'Invalid identifier for product xyz'
                    ],
        )
        """

    def testAPIError(self):
        """Test APIError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
