"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md  # noqa: E501

    The version of the OpenAPI document: 2.1.5
    Contact: ssc@swisssign.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swisssign_ra_api.v2
from swisssign_ra_api.v2.model.certificate_order_status import CertificateOrderStatus


class TestCertificateOrderStatus(unittest.TestCase):
    """CertificateOrderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateOrderStatus(self):
        """Test CertificateOrderStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CertificateOrderStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
