# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swisssign_ra_api.v2.models.certificate_order_status import CertificateOrderStatus

class TestCertificateOrderStatus(unittest.TestCase):
    """CertificateOrderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateOrderStatus(self):
        """Test CertificateOrderStatus"""
        # inst = CertificateOrderStatus()

if __name__ == '__main__':
    unittest.main()
