# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swisssign_ra_api.v2.models.request_overrides import RequestOverrides

class TestRequestOverrides(unittest.TestCase):
    """RequestOverrides unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestOverrides:
        """Test RequestOverrides
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestOverrides`
        """
        model = RequestOverrides()
        if include_optional:
            return RequestOverrides(
                subject_dn = 'c=US,l=Denver,o=Acme Ltd,cn=Sample',
                validity = 1,
                request_extensions = swisssign_ra_api.v2.models.request_extensions.RequestExtensions(
                    microsoft_security_identifier = 'S-1-5-32', 
                    microsoft_policy_template_oid = '2.16.756.3.2.1.0', 
                    request_dns = swisssign_ra_api.v2.models.request_dns.RequestDNS(
                        values = [
                            swisssign_ra_api.v2.models.dns.DNS(
                                dns = 'support.sample.org', 
                                include_base_domain_for_wildcard = True, 
                                include_www_domain = True, )
                            ], ), 
                    request_rfc822 = swisssign_ra_api.v2.models.request_rfc822.RequestRFC822(
                        values = [
                            'sample@sample.org'
                            ], ), 
                    request_upn = swisssign_ra_api.v2.models.request_upn.RequestUPN(
                        values = [
                            'upn@sample.org'
                            ], ), 
                    request_ip = swisssign_ra_api.v2.models.request_ip.RequestIP(
                        values = [
                            '1.1.1.1'
                            ], ), 
                    request_role = swisssign_ra_api.v2.models.request_role.RequestRole(
                        value = 'MY_ROLE', ), 
                    request_device_serial_number = swisssign_ra_api.v2.models.request_device_serial_number.RequestDeviceSerialNumber(
                        value = 'ABCDEF123456XYZ', ), 
                    request_scope = swisssign_ra_api.v2.models.request_scope.RequestScope(
                        value = '00FF01FE02FD03FC', ), )
            )
        else:
            return RequestOverrides(
        )
        """

    def testRequestOverrides(self):
        """Test RequestOverrides"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
