"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md  # noqa: E501

    The version of the OpenAPI document: 2.5.13
    Contact: ssc@swisssign.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import swisssign_ra_api.v2
from swisssign_ra_api.v2.model.certificate_order import CertificateOrder
globals()['CertificateOrder'] = CertificateOrder
from swisssign_ra_api.v2.model.certificate_orders import CertificateOrders


class TestCertificateOrders(unittest.TestCase):
    """CertificateOrders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateOrders(self):
        """Test CertificateOrders"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CertificateOrders()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
