/*
SwissSign RA REST API

See https://github.com/SwissSign-AG/RaApi/README.md

API version: 3.4.4
Contact: ssc@swisssign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swisssign_ra_api.v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestRole{}

// RequestRole struct for RequestRole
type RequestRole struct {
	// Role extension as defined in OID 1.3.6.1.4.1.43121.1.4.2.0.1 (UTF8String)
	Value string `json:"value"`
}

type _RequestRole RequestRole

// NewRequestRole instantiates a new RequestRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestRole(value string) *RequestRole {
	this := RequestRole{}
	this.Value = value
	return &this
}

// NewRequestRoleWithDefaults instantiates a new RequestRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestRoleWithDefaults() *RequestRole {
	this := RequestRole{}
	return &this
}

// GetValue returns the Value field value
func (o *RequestRole) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RequestRole) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RequestRole) SetValue(v string) {
	o.Value = v
}

func (o RequestRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *RequestRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestRole := _RequestRole{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestRole)

	if err != nil {
		return err
	}

	*o = RequestRole(varRequestRole)

	return err
}

type NullableRequestRole struct {
	value *RequestRole
	isSet bool
}

func (v NullableRequestRole) Get() *RequestRole {
	return v.value
}

func (v *NullableRequestRole) Set(val *RequestRole) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestRole) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestRole(val *RequestRole) *NullableRequestRole {
	return &NullableRequestRole{value: val, isSet: true}
}

func (v NullableRequestRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


