/*
SwissSign RA REST API

See https://github.com/SwissSign-AG/RaApi/README.md

API version: 2.5.13
Contact: ssc@swisssign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swisssign_ra_api.v2

import (
	"encoding/json"
)

// Clients struct for Clients
type Clients struct {
	Draw int32 `json:"draw"`
	// Total records, after filtering (i.e. the total number of records after filtering has been applied - not just the number of records being returned for this page of data).
	RecordsFiltered int32 `json:"recordsFiltered"`
	// Total records, before filtering (i.e. the total number of records in the database)
	RecordsTotal int32 `json:"recordsTotal"`
	Data []Client `json:"data"`
}

// NewClients instantiates a new Clients object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClients(draw int32, recordsFiltered int32, recordsTotal int32, data []Client) *Clients {
	this := Clients{}
	this.Draw = draw
	this.RecordsFiltered = recordsFiltered
	this.RecordsTotal = recordsTotal
	this.Data = data
	return &this
}

// NewClientsWithDefaults instantiates a new Clients object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientsWithDefaults() *Clients {
	this := Clients{}
	return &this
}

// GetDraw returns the Draw field value
func (o *Clients) GetDraw() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Draw
}

// GetDrawOk returns a tuple with the Draw field value
// and a boolean to check if the value has been set.
func (o *Clients) GetDrawOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Draw, true
}

// SetDraw sets field value
func (o *Clients) SetDraw(v int32) {
	o.Draw = v
}

// GetRecordsFiltered returns the RecordsFiltered field value
func (o *Clients) GetRecordsFiltered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RecordsFiltered
}

// GetRecordsFilteredOk returns a tuple with the RecordsFiltered field value
// and a boolean to check if the value has been set.
func (o *Clients) GetRecordsFilteredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordsFiltered, true
}

// SetRecordsFiltered sets field value
func (o *Clients) SetRecordsFiltered(v int32) {
	o.RecordsFiltered = v
}

// GetRecordsTotal returns the RecordsTotal field value
func (o *Clients) GetRecordsTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RecordsTotal
}

// GetRecordsTotalOk returns a tuple with the RecordsTotal field value
// and a boolean to check if the value has been set.
func (o *Clients) GetRecordsTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordsTotal, true
}

// SetRecordsTotal sets field value
func (o *Clients) SetRecordsTotal(v int32) {
	o.RecordsTotal = v
}

// GetData returns the Data field value
func (o *Clients) GetData() []Client {
	if o == nil {
		var ret []Client
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Clients) GetDataOk() ([]Client, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *Clients) SetData(v []Client) {
	o.Data = v
}

func (o Clients) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["draw"] = o.Draw
	}
	if true {
		toSerialize["recordsFiltered"] = o.RecordsFiltered
	}
	if true {
		toSerialize["recordsTotal"] = o.RecordsTotal
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableClients struct {
	value *Clients
	isSet bool
}

func (v NullableClients) Get() *Clients {
	return v.value
}

func (v *NullableClients) Set(val *Clients) {
	v.value = val
	v.isSet = true
}

func (v NullableClients) IsSet() bool {
	return v.isSet
}

func (v *NullableClients) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClients(val *Clients) *NullableClients {
	return &NullableClients{value: val, isSet: true}
}

func (v NullableClients) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClients) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


