# coding: utf-8

"""
    SwissSign RA REST API

    See https://github.com/SwissSign-AG/RaApi/README.md

    The version of the OpenAPI document: 3.4.4
    Contact: ssc@swisssign.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "SwissSignRaApi"
VERSION = "3.4.4"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="SwissSign RA REST API",
    author="SwissSign Support",
    author_email="ssc@swisssign.com",
    url="https://github.com/SwissSign-AG/RaApi",
    keywords=["OpenAPI", "OpenAPI-Generator", "SwissSign RA REST API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    See https://github.com/SwissSign-AG/RaApi/README.md
    """,  # noqa: E501
    package_data={"swisssign_ra_api.v2": ["py.typed"]},
)