/*
 * SwissSign RA REST API
 * See https://github.com/SwissSign-AG/RaApi/README.md
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: ssc@swisssign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.JobStatus;
import org.openapitools.client.model.JobType;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CertificateOrderTask
 */
public class CertificateOrderTaskTest {
    private final CertificateOrderTask model = new CertificateOrderTask();

    /**
     * Model tests for CertificateOrderTask
     */
    @Test
    public void testCertificateOrderTask() {
        // TODO: test CertificateOrderTask
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'timeScheduled'
     */
    @Test
    public void timeScheduledTest() {
        // TODO: test timeScheduled
    }

    /**
     * Test the property 'timeStarted'
     */
    @Test
    public void timeStartedTest() {
        // TODO: test timeStarted
    }

    /**
     * Test the property 'timeFinished'
     */
    @Test
    public void timeFinishedTest() {
        // TODO: test timeFinished
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'numberOfExecutions'
     */
    @Test
    public void numberOfExecutionsTest() {
        // TODO: test numberOfExecutions
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
