/*
 * SwissSign RA REST API
 * See https://github.com/SwissSign-AG/RaApi/README.md
 *
 * The version of the OpenAPI document: 2.4.9
 * Contact: ssc@swisssign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Client;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Clients
 */
public class ClientsTest {
    private final Clients model = new Clients();

    /**
     * Model tests for Clients
     */
    @Test
    public void testClients() {
        // TODO: test Clients
    }

    /**
     * Test the property 'draw'
     */
    @Test
    public void drawTest() {
        // TODO: test draw
    }

    /**
     * Test the property 'recordsFiltered'
     */
    @Test
    public void recordsFilteredTest() {
        // TODO: test recordsFiltered
    }

    /**
     * Test the property 'recordsTotal'
     */
    @Test
    public void recordsTotalTest() {
        // TODO: test recordsTotal
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
