/*
 * SwissSign RA REST API
 * See https://github.com/SwissSign-AG/RaApi/README.md
 *
 * The version of the OpenAPI document: 3.4.4
 * Contact: ssc@swisssign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RequestDNS;
import org.openapitools.client.model.RequestDeviceSerialNumber;
import org.openapitools.client.model.RequestIP;
import org.openapitools.client.model.RequestRFC822;
import org.openapitools.client.model.RequestRole;
import org.openapitools.client.model.RequestScope;
import org.openapitools.client.model.RequestUPN;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestExtensions
 */
public class RequestExtensionsTest {
    private final RequestExtensions model = new RequestExtensions();

    /**
     * Model tests for RequestExtensions
     */
    @Test
    public void testRequestExtensions() {
        // TODO: test RequestExtensions
    }

    /**
     * Test the property 'microsoftSecurityIdentifier'
     */
    @Test
    public void microsoftSecurityIdentifierTest() {
        // TODO: test microsoftSecurityIdentifier
    }

    /**
     * Test the property 'microsoftPolicyTemplateOID'
     */
    @Test
    public void microsoftPolicyTemplateOIDTest() {
        // TODO: test microsoftPolicyTemplateOID
    }

    /**
     * Test the property 'requestDNS'
     */
    @Test
    public void requestDNSTest() {
        // TODO: test requestDNS
    }

    /**
     * Test the property 'requestRFC822'
     */
    @Test
    public void requestRFC822Test() {
        // TODO: test requestRFC822
    }

    /**
     * Test the property 'requestUPN'
     */
    @Test
    public void requestUPNTest() {
        // TODO: test requestUPN
    }

    /**
     * Test the property 'requestIP'
     */
    @Test
    public void requestIPTest() {
        // TODO: test requestIP
    }

    /**
     * Test the property 'requestRole'
     */
    @Test
    public void requestRoleTest() {
        // TODO: test requestRole
    }

    /**
     * Test the property 'requestDeviceSerialNumber'
     */
    @Test
    public void requestDeviceSerialNumberTest() {
        // TODO: test requestDeviceSerialNumber
    }

    /**
     * Test the property 'requestScope'
     */
    @Test
    public void requestScopeTest() {
        // TODO: test requestScope
    }

}
