/*
 * SwissSign RA REST API
 * See https://github.com/SwissSign-AG/RaApi/README.md
 *
 * The version of the OpenAPI document: 3.4.4
 * Contact: ssc@swisssign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CertificateOrderStatus;
import org.openapitools.client.model.RevocationReason;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchCertificateOrder
 */
public class SearchCertificateOrderTest {
    private final SearchCertificateOrder model = new SearchCertificateOrder();

    /**
     * Model tests for SearchCertificateOrder
     */
    @Test
    public void testSearchCertificateOrder() {
        // TODO: test SearchCertificateOrder
    }

    /**
     * Test the property 'orderReference'
     */
    @Test
    public void orderReferenceTest() {
        // TODO: test orderReference
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'orderStatus'
     */
    @Test
    public void orderStatusTest() {
        // TODO: test orderStatus
    }

    /**
     * Test the property 'revocationReason'
     */
    @Test
    public void revocationReasonTest() {
        // TODO: test revocationReason
    }

    /**
     * Test the property 'clientReferences'
     */
    @Test
    public void clientReferencesTest() {
        // TODO: test clientReferences
    }

    /**
     * Test the property 'startAfter'
     */
    @Test
    public void startAfterTest() {
        // TODO: test startAfter
    }

    /**
     * Test the property 'startBefore'
     */
    @Test
    public void startBeforeTest() {
        // TODO: test startBefore
    }

    /**
     * Test the property 'attribute'
     */
    @Test
    public void attributeTest() {
        // TODO: test attribute
    }

    /**
     * Test the property 'includeCertificateChain'
     */
    @Test
    public void includeCertificateChainTest() {
        // TODO: test includeCertificateChain
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
